import { useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, Mic, Send, Sparkles, Volume2, CalendarDays, MessagesSquare } from "lucide-react";
import { EventTimelineComponent } from "@/components/timeline/EventTimeline";
import { useAiPlanner } from "@/hooks/useAiPlanner";
import { useVoiceAi } from "@/hooks/useVoiceAi";
import { useTimeline } from "@/hooks/useTimeline";
import type { TimelineConfig } from "@/packages/shared-types/timeline";
import type { AvatarEmotion } from "@/packages/shared-types/avatar";

interface AiEventPlannerWithAvatarProps {
  eventId: string;
  clientId: string;
}

type PlannerPanel = "chat" | "timeline";

const safeNumber = (value: unknown, fallback: number) => {
  const asNumber = Number(value);
  return Number.isFinite(asNumber) ? asNumber : fallback;
};

const parseDateTime = (dateValue: unknown, timeValue: unknown, fallbackHour: number) => {
  if (typeof dateValue === "string" && dateValue.trim()) {
    const time = typeof timeValue === "string" && timeValue.trim() ? timeValue : `${String(fallbackHour).padStart(2, "0")}:00`;
    const parsed = new Date(`${dateValue}T${time}`);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  const fallback = new Date();
  fallback.setHours(fallbackHour, 0, 0, 0);
  return fallback;
};

export function AiEventPlannerWithAvatar({ eventId, clientId }: AiEventPlannerWithAvatarProps) {
  const bottomRef = useRef<HTMLDivElement>(null);
  const [userMessage, setUserMessage] = useState("");
  const [inputMode, setInputMode] = useState<"text" | "voice">("text");
  const [activePanel, setActivePanel] = useState<PlannerPanel>("chat");
  const [avatarEmotion, setAvatarEmotion] = useState<AvatarEmotion>("idle");
  const [isProcessing, setIsProcessing] = useState(false);
  const [autoSpeak, setAutoSpeak] = useState(false);
  const [lastSpokenMessageId, setLastSpokenMessageId] = useState<string | null>(null);
  const [hasAutoGeneratedTimeline, setHasAutoGeneratedTimeline] = useState(false);

  const { state, startConversation, sendMessage: sendPlannerMessage } = useAiPlanner();
  const {
    isListening,
    isSpeaking,
    transcript,
    isInitialized: voiceReady,
    startListening: voiceStartListening,
    stopListening: voiceStopListening,
    speak,
    clearTranscript,
  } = useVoiceAi(state.conversationId ?? eventId, {
    mode: "push-to-talk",
    onTranscript: (value) => {
      const trimmed = value.trim();
      if (trimmed) setUserMessage(trimmed);
    },
  });

  const {
    timeline,
    optimization,
    djSchedule,
    isLoading: timelineLoading,
    error: timelineError,
    generateTimeline,
  } = useTimeline();

  const messages = state.messages;
  const plannerLoading = state.loading;
  const plannerError = state.error;

  const latestAssistantMessage = useMemo(() => {
    for (let i = messages.length - 1; i >= 0; i -= 1) {
      if (messages[i].role === "assistant") return messages[i];
    }
    return null;
  }, [messages]);

  const timelineConfig = useMemo<TimelineConfig>(() => {
    const collected = state.collectedData || {};
    const eventDetails = collected.eventDetails || {};
    const style = collected.eventStyle || {};
    const rawType = String(eventDetails.type || collected.event_type || "wedding").toLowerCase();
    const mappedType: TimelineConfig["eventType"] =
      rawType === "corporate" || rawType === "birthday" || rawType === "anniversary" || rawType === "graduation"
        ? rawType
        : "wedding";

    const startTime = parseDateTime(eventDetails.date || collected.event_date, eventDetails.startTime || collected.start_time, 15);
    const endTime = parseDateTime(eventDetails.date || collected.event_date, eventDetails.estimatedEndTime || collected.end_time, 23);
    const computedDuration = Math.max(180, Math.floor((endTime.getTime() - startTime.getTime()) / 60000));

    return {
      eventType: mappedType,
      startTime,
      endTime,
      eventDuration: computedDuration,
      guestCount: safeNumber(eventDetails.guestCount || collected.guest_count, 120),
      venue: String(collected.venue_name || eventDetails.venue || "Main Venue"),
      hasSpecialPerformances: true,
      hasSpeeches: true,
      musicGenre: Array.isArray(style.musicGenres) && style.musicGenres[0] ? String(style.musicGenres[0]) : "Open Format",
      isSemiOutdoor: false,
    };
  }, [state.collectedData]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    if (isSpeaking) {
      setAvatarEmotion("speaking");
    } else if (isListening) {
      setAvatarEmotion("listening");
    } else if (isProcessing || plannerLoading || timelineLoading) {
      setAvatarEmotion("thinking");
    } else if (state.isComplete) {
      setAvatarEmotion("celebrating");
    } else {
      setAvatarEmotion("idle");
    }
  }, [isListening, isSpeaking, isProcessing, plannerLoading, timelineLoading, state.isComplete]);

  useEffect(() => {
    if (!state.conversationId) {
      void startConversation(eventId);
    }
  }, [eventId, state.conversationId, startConversation]);

  useEffect(() => {
    if (
      autoSpeak &&
      voiceReady &&
      latestAssistantMessage &&
      latestAssistantMessage.id !== lastSpokenMessageId &&
      !isSpeaking
    ) {
      setLastSpokenMessageId(latestAssistantMessage.id);
      void speak(latestAssistantMessage.content);
    }
  }, [autoSpeak, voiceReady, latestAssistantMessage, lastSpokenMessageId, isSpeaking, speak]);

  useEffect(() => {
    if (state.isComplete && !timeline && !timelineLoading && !hasAutoGeneratedTimeline) {
      setHasAutoGeneratedTimeline(true);
      setActivePanel("timeline");
      void generateTimeline(timelineConfig, eventId);
    }
  }, [eventId, generateTimeline, hasAutoGeneratedTimeline, state.isComplete, timeline, timelineConfig, timelineLoading]);

  const handleSendMessage = async () => {
    const message = userMessage.trim();
    if (!message) return;

    setUserMessage("");
    setIsProcessing(true);
    try {
      await sendPlannerMessage(message);
      clearTranscript();
    } finally {
      setIsProcessing(false);
    }
  };

  const handleVoiceInput = () => {
    if (isListening) {
      voiceStopListening();
    } else {
      voiceStartListening();
    }
  };

  const handleSubmitVoiceMessage = async () => {
    const message = transcript.trim();
    if (!message) return;
    setIsProcessing(true);
    try {
      await sendPlannerMessage(message);
      clearTranscript();
      setUserMessage("");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleGenerateTimeline = async () => {
    setActivePanel("timeline");
    await generateTimeline(timelineConfig, eventId);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-purple-950 to-slate-950">
      <div className="container mx-auto px-4 py-6 max-w-6xl">
        <div className="mb-6">
          <h1 className="font-display text-3xl font-bold gradient-text mb-2">Beatkulture Event Planner</h1>
          <p className="text-muted-foreground">Avatar, chat, voice, and timeline in one guided experience</p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}>
            <Card variant="glass" className="h-full overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg flex items-center gap-2">
                  <Sparkles className="w-4 h-4" /> Your AI Host
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="relative aspect-square rounded-xl border border-border/50 bg-black/40 flex items-center justify-center overflow-hidden">
                  <motion.div
                    animate={{
                      scale: avatarEmotion === "listening" || avatarEmotion === "speaking" ? [1, 1.08, 1] : 1,
                    }}
                    transition={{ duration: 1.2, repeat: Infinity }}
                    className={`w-36 h-36 rounded-full blur-[1px] ${
                      avatarEmotion === "speaking"
                        ? "bg-green-500/60"
                        : avatarEmotion === "thinking"
                          ? "bg-purple-500/60"
                          : avatarEmotion === "listening"
                            ? "bg-blue-500/60"
                            : avatarEmotion === "celebrating"
                              ? "bg-orange-500/60"
                              : "bg-slate-500/40"
                    }`}
                  />
                  <div className="absolute inset-0 flex items-center justify-center text-sm text-slate-200 font-medium">
                    {avatarEmotion === "celebrating" ? "Plan Ready 🎉" : `Emotion: ${avatarEmotion}`}
                  </div>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="outline" className="bg-black/40">
                    Client: {clientId.slice(0, 8)}...
                  </Badge>
                  <Badge variant="outline" className="bg-black/40">
                    Event: {eventId.slice(0, 8)}...
                  </Badge>
                </div>
                <Button
                  type="button"
                  variant={autoSpeak ? "default" : "outline"}
                  size="sm"
                  className="w-full"
                  onClick={() => setAutoSpeak((value) => !value)}
                  disabled={!voiceReady}
                >
                  <Volume2 className="w-4 h-4 mr-2" />
                  {autoSpeak ? "Voice Playback On" : "Enable Voice Playback"}
                </Button>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="flex flex-col"
          >
            <Card variant="glass" className="flex-1 flex flex-col overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg">Planning Workspace</CardTitle>
                <CardDescription>Switch between live conversation and generated timeline</CardDescription>
              </CardHeader>

              <div className="px-6 pb-2 flex gap-2">
                <Badge
                  variant={activePanel === "chat" ? "default" : "outline"}
                  className="cursor-pointer"
                  onClick={() => setActivePanel("chat")}
                >
                  <MessagesSquare className="w-3 h-3 mr-1" />
                  Chat
                </Badge>
                <Badge
                  variant={activePanel === "timeline" ? "default" : "outline"}
                  className="cursor-pointer"
                  onClick={() => setActivePanel("timeline")}
                >
                  <CalendarDays className="w-3 h-3 mr-1" />
                  Timeline
                </Badge>
              </div>

              {activePanel === "chat" ? (
                <CardContent className="flex-1 overflow-y-auto space-y-4 pb-4">
                  {plannerError && (
                    <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30 text-sm text-destructive">
                      {plannerError}
                    </div>
                  )}

                  {messages.length === 0 && !plannerLoading && (
                    <div className="flex items-center justify-center h-32 text-muted-foreground">
                      <p className="text-center">
                        <span className="block font-semibold mb-2">Welcome!</span>
                        <span className="text-sm">Let&apos;s start planning your perfect event.</span>
                      </p>
                    </div>
                  )}

                  {messages.map((msg) => (
                    <motion.div
                      key={msg.id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3 }}
                      className={`flex gap-2 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                    >
                      <div
                        className={`max-w-xs px-4 py-2 rounded-lg ${
                          msg.role === "user"
                            ? "bg-primary/20 text-primary border border-primary/40"
                            : "bg-purple-500/20 text-purple-200 border border-purple-500/40"
                        }`}
                      >
                        <p className="text-sm leading-relaxed">{msg.content}</p>
                      </div>
                    </motion.div>
                  ))}

                  {isProcessing && (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex gap-2">
                      <div className="bg-purple-500/20 text-purple-200 border border-purple-500/40 px-4 py-2 rounded-lg">
                        <div className="flex items-center gap-2">
                          <Loader2 className="w-3 h-3 animate-spin" />
                          <span className="text-sm">Avatar is thinking...</span>
                        </div>
                      </div>
                    </motion.div>
                  )}

                  <div ref={bottomRef} />
                </CardContent>
              ) : (
                <CardContent className="flex-1 overflow-y-auto space-y-4 pb-4">
                  {timelineError && (
                    <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30 text-sm text-destructive">
                      {timelineError}
                    </div>
                  )}
                  {!timeline && (
                    <Button onClick={() => void handleGenerateTimeline()} disabled={timelineLoading} variant="hero" className="w-full">
                      {timelineLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <CalendarDays className="w-4 h-4 mr-2" />}
                      Generate Timeline
                    </Button>
                  )}
                  <EventTimelineComponent timeline={timeline} djSchedule={djSchedule} isLoading={timelineLoading} />
                </CardContent>
              )}

              {activePanel === "chat" && (
                <div className="border-t border-border/50 p-4 space-y-3">
                  {inputMode === "voice" && (
                    <div className="space-y-2">
                      {isListening && (
                        <div className="p-3 rounded-lg bg-blue-500/10 border border-blue-500/30">
                          <div className="flex items-center gap-2 text-blue-300 text-sm">
                            <Loader2 className="w-3 h-3 animate-spin" />
                            Listening...
                          </div>
                        </div>
                      )}

                      {transcript && (
                        <div className="p-3 rounded-lg bg-slate-700/40 border border-border">
                          <p className="text-sm text-muted-foreground">{transcript}</p>
                        </div>
                      )}

                      {transcript && !isListening && (
                        <Button onClick={() => void handleSubmitVoiceMessage()} disabled={isProcessing} className="w-full" variant="hero" size="sm">
                          <Send className="w-3 h-3 mr-2" />
                          Send Voice Message
                        </Button>
                      )}
                    </div>
                  )}

                  {inputMode === "text" && (
                    <div className="flex gap-2">
                      <input
                        type="text"
                        placeholder="Type your response..."
                        value={userMessage}
                        onChange={(e) => setUserMessage(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === "Enter" && !e.shiftKey) {
                            e.preventDefault();
                            void handleSendMessage();
                          }
                        }}
                        disabled={isProcessing}
                        className="flex-1 px-3 py-2 rounded-lg bg-slate-900 border border-border/50 text-sm placeholder-muted-foreground focus:outline-none focus:border-primary/50 transition disabled:opacity-50"
                      />
                      <Button onClick={() => void handleSendMessage()} disabled={isProcessing || !userMessage.trim()} size="sm" variant="hero">
                        <Send className="w-3 h-3" />
                      </Button>
                    </div>
                  )}

                  <div className="flex gap-2 justify-center">
                    <Badge
                      variant={inputMode === "text" ? "default" : "outline"}
                      className="cursor-pointer"
                      onClick={() => setInputMode("text")}
                    >
                      Text
                    </Badge>
                    <Badge
                      variant={inputMode === "voice" ? "default" : "outline"}
                      className={`cursor-pointer ${voiceReady ? "" : "opacity-50"}`}
                      onClick={() => voiceReady && setInputMode("voice")}
                    >
                      <Mic className="w-3 h-3 mr-1" />
                      Voice
                    </Badge>
                  </div>

                  {inputMode === "voice" && voiceReady && !isListening && (
                    <Button onClick={handleVoiceInput} disabled={isProcessing} className="w-full" variant="outline" size="sm">
                      <Mic className="w-3 h-3 mr-2" />
                      Start Listening
                    </Button>
                  )}

                  {isListening && (
                    <Button onClick={handleVoiceInput} disabled={isProcessing} className="w-full" variant="destructive" size="sm">
                      Stop Listening
                    </Button>
                  )}

                  {!timeline && (
                    <Button onClick={() => void handleGenerateTimeline()} disabled={timelineLoading} className="w-full" variant="outline" size="sm">
                      <CalendarDays className="w-3 h-3 mr-2" />
                      Generate Timeline from Conversation
                    </Button>
                  )}
                </div>
              )}
            </Card>

            <div className="mt-3 flex gap-2 justify-center flex-wrap">
              {plannerLoading && (
                <Badge variant="outline" className="bg-purple-500/20">
                  <Loader2 className="w-2 h-2 mr-1 animate-spin" /> Planning...
                </Badge>
              )}
              {timelineLoading && (
                <Badge variant="outline" className="bg-orange-500/20">
                  <Loader2 className="w-2 h-2 mr-1 animate-spin" /> Building timeline...
                </Badge>
              )}
              {isSpeaking && (
                <Badge variant="outline" className="bg-green-500/20">
                  <div className="w-2 h-2 mr-1 rounded-full bg-green-500" /> Speaking
                </Badge>
              )}
              {voiceReady && (
                <Badge variant="outline" className="bg-blue-500/20">
                  🎤 Voice Ready
                </Badge>
              )}
              {optimization && (
                <Badge variant="outline" className="bg-amber-500/20">
                  Timeline Score: {optimization.score}
                </Badge>
              )}
              {state.isComplete && <Badge className="bg-orange-500/20">✅ Plan Complete</Badge>}
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
