import { useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, Mic, Send, Sparkles, Volume2, CalendarDays, MessagesSquare, Image, SmilePlus, Clapperboard } from "lucide-react";
import { EventTimelineComponent } from "@/components/timeline/EventTimeline";
import { EventVisualizationPanel } from "@/components/visualization/EventVisualizationPanel";
import { HumorAssistantPanel } from "@/components/humor/HumorAssistantPanel";
import { EntertainmentMomentWidget } from "@/components/humor/EntertainmentMomentWidget";
import { VirtualRehearsalPanel } from "@/components/rehearsal/VirtualRehearsalPanel";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useAiPlanner } from "@/hooks/useAiPlanner";
import { useVoiceAi } from "@/hooks/useVoiceAi";
import { useTimeline } from "@/hooks/useTimeline";
import { useVisualization } from "@/hooks/useVisualization";
import { useHumorAssistant } from "@/hooks/useHumorAssistant";
import { useRehearsal } from "@/hooks/useRehearsal";
import { useAiPersonality } from "@/hooks/useAiPersonality";
import { useVoicePreferences } from "@/hooks/useVoicePreferences";
import { CinematicAmbient } from "@/components/CinematicAmbient";
import { BeatkultureMascot } from "@/components/BeatkultureMascot";
import type { TimelineConfig } from "@/packages/shared-types/timeline";
import type { AvatarEmotion } from "@/packages/shared-types/avatar";

interface AiEventPlannerWithAvatarProps {
  eventId: string;
  clientId: string;
}

type PlannerPanel = "chat" | "timeline" | "visualization" | "rehearsal" | "humor";
type ReviewArtifact = "timeline" | "visualization" | "rehearsal";
type ArtifactReviewStatus = "pending" | "approved" | "changes_requested";

const safeNumber = (value: unknown, fallback: number) => {
  const asNumber = Number(value);
  return Number.isFinite(asNumber) ? asNumber : fallback;
};

const parseDateTime = (dateValue: unknown, timeValue: unknown, fallbackHour: number) => {
  if (typeof dateValue === "string" && dateValue.trim()) {
    const time = typeof timeValue === "string" && timeValue.trim() ? timeValue : `${String(fallbackHour).padStart(2, "0")}:00`;
    const parsed = new Date(`${dateValue}T${time}`);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  const fallback = new Date();
  fallback.setHours(fallbackHour, 0, 0, 0);
  return fallback;
};

export function AiEventPlannerWithAvatar({ eventId, clientId }: AiEventPlannerWithAvatarProps) {
  const { user, profile } = useAuth();
  const bottomRef = useRef<HTMLDivElement>(null);
  const [userMessage, setUserMessage] = useState("");
  const [inputMode, setInputMode] = useState<"text" | "voice">("text");
  const [activePanel, setActivePanel] = useState<PlannerPanel>("chat");
  const [avatarEmotion, setAvatarEmotion] = useState<AvatarEmotion>("idle");
  const [isProcessing, setIsProcessing] = useState(false);
  const [autoSpeak, setAutoSpeak] = useState(false);
  const [speechEnergy, setSpeechEnergy] = useState(0);
  const [speechViseme, setSpeechViseme] = useState("rest");
  const [lastSpokenMessageId, setLastSpokenMessageId] = useState<string | null>(null);
  const [hasAutoGeneratedTimeline, setHasAutoGeneratedTimeline] = useState(false);
  const [reviewSubmitting, setReviewSubmitting] = useState<ReviewArtifact | null>(null);
  const [artifactReviewStatus, setArtifactReviewStatus] = useState<Record<ReviewArtifact, ArtifactReviewStatus>>({
    timeline: "pending",
    visualization: "pending",
    rehearsal: "pending",
  });
  const [artifactReviewNotes, setArtifactReviewNotes] = useState<Record<ReviewArtifact, string>>({
    timeline: "",
    visualization: "",
    rehearsal: "",
  });

  const { personality, setPersonality, autoSwitchMode } = useAiPersonality(clientId);
  const { preferences, setEnabled } = useVoicePreferences(clientId);

  const { state, startConversation, sendMessage: sendPlannerMessage } = useAiPlanner();
  const {
    isListening,
    isSpeaking,
    transcript,
    isInitialized: voiceReady,
    startListening: voiceStartListening,
    stopListening: voiceStopListening,
    speak,
    clearTranscript,
  } = useVoiceAi(state.conversationId ?? eventId, {
    mode: "push-to-talk",
    voiceEnabled: preferences.enabled,
    voiceName: preferences.voiceName,
    speakingRate: preferences.speakingRate,
    onSpeechProgress: ({ energy, viseme }) => {
      setSpeechEnergy(energy);
      setSpeechViseme(viseme);
    },
    onTranscript: (value) => {
      const trimmed = value.trim();
      if (trimmed) setUserMessage(trimmed);
    },
  });

  const {
    timeline,
    optimization,
    djSchedule,
    isLoading: timelineLoading,
    error: timelineError,
    generateTimeline,
  } = useTimeline();
  const {
    storyboard,
    isLoading: visualizationLoading,
    error: visualizationError,
    generateStoryboard,
  } = useVisualization();
  const {
    rehearsal,
    isLoading: rehearsalLoading,
    error: rehearsalError,
    generateRehearsal,
  } = useRehearsal();
  const humorContext = useMemo(() => {
    const collected = state.collectedData || {};
    const wedding = collected.weddingDetails || {};
    const style = collected.eventStyle || {};
    return {
      eventType: String(collected.event_type || collected.eventDetails?.type || "wedding"),
      audienceAgeGroup: "mixed" as const,
      eventFormality: "semi-formal" as const,
      culturalContext: wedding.culturalTraditions?.join(", "),
      coupleNames: [wedding.partnerA, wedding.partnerB].filter(Boolean),
      howTheyMet: collected.clientDetails?.timeline,
      sharedHobbies: style.musicGenres,
      funnyStories: wedding.specialMoments,
      eventTheme: style.specialTheme,
      weddingPartyInfo: collected.entertainmentInfo?.additionalServices,
    };
  }, [state.collectedData]);
  const {
    suggestions: humorSuggestions,
    speechDraft,
    moment,
    widgetEnabled,
    widgetMinimized,
    generateHumor,
    generateSpeech,
    refreshMoment,
    toggleWidgetEnabled,
    toggleWidgetMinimized,
  } = useHumorAssistant(humorContext, personality);

  const messages = state.messages;
  const plannerLoading = state.loading;
  const plannerError = state.error;

  const latestAssistantMessage = useMemo(() => {
    for (let i = messages.length - 1; i >= 0; i -= 1) {
      if (messages[i].role === "assistant") return messages[i];
    }
    return null;
  }, [messages]);

  const timelineConfig = useMemo<TimelineConfig>(() => {
    const collected = state.collectedData || {};
    const eventDetails = collected.eventDetails || {};
    const style = collected.eventStyle || {};
    const rawType = String(eventDetails.type || collected.event_type || "wedding").toLowerCase();
    const mappedType: TimelineConfig["eventType"] =
      rawType === "corporate" || rawType === "birthday" || rawType === "anniversary" || rawType === "graduation"
        ? rawType
        : "wedding";

    const startTime = parseDateTime(eventDetails.date || collected.event_date, eventDetails.startTime || collected.start_time, 15);
    const endTime = parseDateTime(eventDetails.date || collected.event_date, eventDetails.estimatedEndTime || collected.end_time, 23);
    const computedDuration = Math.max(180, Math.floor((endTime.getTime() - startTime.getTime()) / 60000));

    return {
      eventType: mappedType,
      startTime,
      endTime,
      eventDuration: computedDuration,
      guestCount: safeNumber(eventDetails.guestCount || collected.guest_count, 120),
      venue: String(collected.venue_name || eventDetails.venue || "Main Venue"),
      hasSpecialPerformances: true,
      hasSpeeches: true,
      musicGenre: Array.isArray(style.musicGenres) && style.musicGenres[0] ? String(style.musicGenres[0]) : "Open Format",
      isSemiOutdoor: false,
    };
  }, [state.collectedData]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    if (isSpeaking) {
      setAvatarEmotion("speaking");
    } else if (isListening) {
      setAvatarEmotion("listening");
    } else if (isProcessing || plannerLoading || timelineLoading || visualizationLoading || rehearsalLoading) {
      setAvatarEmotion("thinking");
    } else if (state.isComplete) {
      setAvatarEmotion("celebrating");
    } else {
      setAvatarEmotion("idle");
    }
  }, [isListening, isSpeaking, isProcessing, plannerLoading, timelineLoading, visualizationLoading, rehearsalLoading, state.isComplete]);

  useEffect(() => {
    autoSwitchMode({
      activePanel,
      eventType: String(state.collectedData?.event_type || state.collectedData?.eventDetails?.type || ""),
      wantsJokes: activePanel === "humor",
    });
  }, [activePanel, autoSwitchMode, state.collectedData]);

  useEffect(() => {
    if (!state.conversationId) {
      void startConversation(eventId);
    }
  }, [eventId, state.conversationId, startConversation]);

  useEffect(() => {
    if (
      autoSpeak &&
      voiceReady &&
      latestAssistantMessage &&
      latestAssistantMessage.id !== lastSpokenMessageId &&
      !isSpeaking
    ) {
      setLastSpokenMessageId(latestAssistantMessage.id);
      void speak(latestAssistantMessage.content);
    }
  }, [autoSpeak, voiceReady, latestAssistantMessage, lastSpokenMessageId, isSpeaking, speak]);

  useEffect(() => {
    if (state.isComplete && !timeline && !timelineLoading && !hasAutoGeneratedTimeline) {
      setHasAutoGeneratedTimeline(true);
      setActivePanel("timeline");
      void generateTimeline(timelineConfig, eventId);
    }
  }, [eventId, generateTimeline, hasAutoGeneratedTimeline, state.isComplete, timeline, timelineConfig, timelineLoading]);

  const handleSendMessage = async () => {
    const message = userMessage.trim();
    if (!message) return;

    setUserMessage("");
    setIsProcessing(true);
    try {
      await sendPlannerMessage(message);
      clearTranscript();
    } finally {
      setIsProcessing(false);
    }
  };

  const handleVoiceInput = () => {
    if (isListening) {
      voiceStopListening();
    } else {
      voiceStartListening();
    }
  };

  const handleSubmitVoiceMessage = async () => {
    const message = transcript.trim();
    if (!message) return;
    setIsProcessing(true);
    try {
      await sendPlannerMessage(message);
      clearTranscript();
      setUserMessage("");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleGenerateTimeline = async () => {
    setActivePanel("timeline");
    await generateTimeline(timelineConfig, eventId);
  };

  const handleGenerateVisualization = async () => {
    if (!timeline) return;
    setActivePanel("visualization");
    await generateStoryboard(timeline);
  };

  const handleGenerateRehearsal = async () => {
    if (!timeline) {
      await handleGenerateTimeline();
      return;
    }
    const board = storyboard || (await generateStoryboard(timeline));
    setActivePanel("rehearsal");
    await generateRehearsal(eventId, timeline, board);
  };

  const getArtifactSummary = (artifact: ReviewArtifact) => {
    if (artifact === "timeline") {
      return timeline ? `${timeline.phases.length} phases with ${timeline.totalDuration} total minutes.` : "Timeline not generated yet.";
    }
    if (artifact === "visualization") {
      return storyboard ? `${storyboard.scenes.length} scenes across generated event visuals.` : "Visual storyboard not generated yet.";
    }
    return rehearsal ? `${rehearsal.runtimeSeconds}s rehearsal with ${rehearsal.cues.length} cues.` : "Virtual rehearsal not generated yet.";
  };

  const handleArtifactReview = async (artifact: ReviewArtifact, status: ArtifactReviewStatus) => {
    const note = artifactReviewNotes[artifact].trim();
    if (status === "changes_requested" && !note) {
      toast({
        title: "Add requested changes",
        description: "Please include what should be changed before submitting review feedback.",
        variant: "destructive",
      });
      return;
    }
    if (!user?.id || !profile?.full_name) {
      toast({
        title: "Unable to submit review",
        description: "Your account details are required to submit planner feedback.",
        variant: "destructive",
      });
      return;
    }

    const label = artifact === "timeline" ? "Timeline" : artifact === "visualization" ? "Visuals" : "Rehearsal";
    const decisionLabel = status === "approved" ? "approved" : "requested changes for";
    const summary = getArtifactSummary(artifact);
    const detail = note ? `\nFeedback: ${note}` : "";
    const reviewMessage = `[Planner Review] ${label} ${decisionLabel} by ${profile.full_name}.${detail}\nSummary: ${summary}`;

    setReviewSubmitting(artifact);
    try {
      const [messageResult, notificationResult] = await Promise.all([
        supabase.from("quote_messages").insert({
          quote_id: eventId,
          sender_id: user.id,
          sender_role: "client",
          sender_name: profile.full_name,
          message: reviewMessage,
        } as any),
        supabase.from("admin_notifications").insert({
          type: "planner_review_feedback",
          title: `Planner ${label} ${status === "approved" ? "approved" : "changes requested"}`,
          message: `${profile.full_name} submitted ${status === "approved" ? "approval" : "change request"} for ${label.toLowerCase()} in planner ${eventId}.`,
          quote_id: eventId,
          email: user.email ?? null,
        } as any),
      ]);

      if (messageResult.error) {
        throw new Error(messageResult.error.message);
      }
      if (notificationResult.error) {
        throw new Error(notificationResult.error.message);
      }

      setArtifactReviewStatus((previous) => ({ ...previous, [artifact]: status }));
      setArtifactReviewNotes((previous) => ({ ...previous, [artifact]: "" }));
      toast({
        title: status === "approved" ? `${label} approved` : `Change request sent for ${label}`,
        description: "Your review feedback has been shared with the Beatkulture team.",
      });
    } catch (error) {
      toast({
        title: "Review submission failed",
        description: error instanceof Error ? error.message : "Unable to submit review feedback.",
        variant: "destructive",
      });
    } finally {
      setReviewSubmitting(null);
    }
  };

  return (
    <div className="cinematic-shell min-h-screen">
      <CinematicAmbient intensity="medium" />
      <div className="container mx-auto px-4 py-6 max-w-6xl">
        <div className="mb-6">
          <h1 className="font-display text-3xl font-bold gradient-text mb-2">Beatkulture Event Planner</h1>
          <p className="text-muted-foreground">Avatar, chat, voice, and timeline in one guided experience</p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}>
            <Card variant="glass" className="feature-card-luxe h-full overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg flex items-center gap-2">
                  <Sparkles className="w-4 h-4" /> Your AI Host
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="relative aspect-square rounded-xl border border-primary/20 bg-black/45 flex items-center justify-center overflow-hidden">
                  <motion.div
                    animate={{ opacity: [0.45, 0.8, 0.45], scale: [1, 1.06, 1] }}
                    transition={{ duration: 2.3, repeat: Infinity }}
                    className="absolute inset-8 rounded-full bg-gradient-to-br from-secondary/30 via-primary/10 to-accent/30 blur-2xl"
                  />
                  <BeatkultureMascot
                    mood={
                      avatarEmotion === "celebrating"
                        ? "celebrating"
                        : avatarEmotion === "listening"
                          ? "listening"
                          : avatarEmotion === "thinking"
                            ? "thinking"
                            : isSpeaking
                              ? "speaking"
                              : "idle"
                    }
                    speechEnergy={speechEnergy}
                    viseme={speechViseme}
                    className="z-10"
                  />
                  <div className="absolute bottom-3 rounded-full border border-primary/30 bg-black/55 px-3 py-1 text-xs text-primary">
                    {avatarEmotion === "celebrating" ? "Milestone celebration" : `Host mode: ${avatarEmotion}`}
                  </div>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="outline" className="bg-black/40">
                    Client: {clientId.slice(0, 8)}...
                  </Badge>
                  <Badge variant="outline" className="bg-black/40">
                    Event: {eventId.slice(0, 8)}...
                  </Badge>
                </div>
                <Button
                  type="button"
                  variant={autoSpeak ? "default" : "outline"}
                  size="sm"
                  className="w-full"
                  onClick={() => setAutoSpeak((value) => !value)}
                  disabled={!voiceReady}
                >
                  <Volume2 className="w-4 h-4 mr-2" />
                  {autoSpeak ? "Voice Playback On" : "Enable Voice Playback"}
                </Button>
                <Button
                  type="button"
                  variant={preferences.enabled ? "default" : "outline"}
                  size="sm"
                  className="w-full"
                  onClick={() => setEnabled(!preferences.enabled)}
                >
                  <Mic className="w-4 h-4 mr-2" />
                  {preferences.enabled ? "Voice Enabled" : "Voice Disabled"}
                </Button>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="flex flex-col"
          >
            <Card variant="glass" className="feature-card-luxe flex-1 flex flex-col overflow-hidden">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg">Planning Workspace</CardTitle>
                <CardDescription>Switch between live conversation and generated timeline</CardDescription>
              </CardHeader>

              <div className="px-6 pb-2 flex gap-2">
                <Badge
                  variant={activePanel === "chat" ? "default" : "outline"}
                  className="cursor-pointer"
                  onClick={() => setActivePanel("chat")}
                >
                  <MessagesSquare className="w-3 h-3 mr-1" />
                  Chat
                </Badge>
                <Badge
                  variant={activePanel === "timeline" ? "default" : "outline"}
                  className="cursor-pointer"
                  onClick={() => setActivePanel("timeline")}
                >
                  <CalendarDays className="w-3 h-3 mr-1" />
                  Timeline
                </Badge>
                <Badge
                  variant={activePanel === "visualization" ? "default" : "outline"}
                  className="cursor-pointer"
                  onClick={() => setActivePanel("visualization")}
                >
                  <Image className="w-3 h-3 mr-1" />
                  Visuals
                </Badge>
                <Badge
                  variant={activePanel === "rehearsal" ? "default" : "outline"}
                  className="cursor-pointer"
                  onClick={() => setActivePanel("rehearsal")}
                >
                  <Clapperboard className="w-3 h-3 mr-1" />
                  Rehearsal
                </Badge>
                <Badge
                  variant={activePanel === "humor" ? "default" : "outline"}
                  className="cursor-pointer"
                  onClick={() => setActivePanel("humor")}
                >
                  <SmilePlus className="w-3 h-3 mr-1" />
                  Humor
                </Badge>
              </div>

              {activePanel === "chat" ? (
                <CardContent className="flex-1 overflow-y-auto space-y-4 pb-4">
                  {plannerError && (
                    <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30 text-sm text-destructive">
                      {plannerError}
                    </div>
                  )}

                  {messages.length === 0 && !plannerLoading && (
                    <div className="flex items-center justify-center h-32 text-muted-foreground">
                      <p className="text-center">
                        <span className="block font-semibold mb-2">Welcome!</span>
                        <span className="text-sm">Let&apos;s start planning your perfect event.</span>
                      </p>
                    </div>
                  )}

                  {messages.map((msg) => (
                    <motion.div
                      key={msg.id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3 }}
                      className={`flex gap-2 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                    >
                      <div
                        className={`max-w-xs px-4 py-2 rounded-lg ${
                          msg.role === "user"
                            ? "bg-primary/20 text-primary border border-primary/40"
                            : "bg-purple-500/20 text-purple-200 border border-purple-500/40"
                        }`}
                      >
                        <p className="text-sm leading-relaxed">{msg.content}</p>
                      </div>
                    </motion.div>
                  ))}

                  {isProcessing && (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex gap-2">
                      <div className="bg-purple-500/20 text-purple-200 border border-purple-500/40 px-4 py-2 rounded-lg">
                        <div className="flex items-center gap-2">
                          <Loader2 className="w-3 h-3 animate-spin" />
                          <span className="text-sm">Avatar is thinking...</span>
                        </div>
                      </div>
                    </motion.div>
                  )}

                  <div ref={bottomRef} />
                </CardContent>
              ) : activePanel === "timeline" ? (
                <CardContent className="flex-1 overflow-y-auto space-y-4 pb-4">
                  {timelineError && (
                    <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30 text-sm text-destructive">
                      {timelineError}
                    </div>
                  )}
                  {!timeline && (
                    <Button onClick={() => void handleGenerateTimeline()} disabled={timelineLoading} variant="hero" className="w-full">
                      {timelineLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <CalendarDays className="w-4 h-4 mr-2" />}
                      Generate Timeline
                    </Button>
                  )}
                  <EventTimelineComponent timeline={timeline} djSchedule={djSchedule} isLoading={timelineLoading} />
                  {timeline && (
                    <div className="space-y-2 rounded-lg border border-border/60 p-3">
                      <p className="text-sm font-semibold">Client review</p>
                      <p className="text-xs text-muted-foreground">Approve this timeline or request changes before final sign-off.</p>
                      <Textarea
                        value={artifactReviewNotes.timeline}
                        onChange={(event) => setArtifactReviewNotes((previous) => ({ ...previous, timeline: event.target.value }))}
                        placeholder="Optional feedback (required if requesting changes)"
                        className="min-h-20"
                      />
                      <div className="flex gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          disabled={reviewSubmitting === "timeline"}
                          onClick={() => void handleArtifactReview("timeline", "approved")}
                        >
                          Approve timeline
                        </Button>
                        <Button
                          variant="destructive"
                          size="sm"
                          disabled={reviewSubmitting === "timeline"}
                          onClick={() => void handleArtifactReview("timeline", "changes_requested")}
                        >
                          Request changes
                        </Button>
                      </div>
                    </div>
                  )}
                </CardContent>
              ) : activePanel === "visualization" ? (
                <CardContent className="flex-1 overflow-y-auto space-y-4 pb-4">
                  {visualizationError && (
                    <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30 text-sm text-destructive">
                      {visualizationError}
                    </div>
                  )}
                  {!storyboard && (
                    <Button
                      onClick={() => void handleGenerateVisualization()}
                      disabled={visualizationLoading || !timeline}
                      variant="hero"
                      className="w-full"
                    >
                      {visualizationLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Image className="w-4 h-4 mr-2" />}
                      Generate Event Visuals
                    </Button>
                  )}
                  <EventVisualizationPanel storyboard={storyboard} isLoading={visualizationLoading} />
                  {storyboard && (
                    <div className="space-y-2 rounded-lg border border-border/60 p-3">
                      <p className="text-sm font-semibold">Client review</p>
                      <p className="text-xs text-muted-foreground">Approve generated visuals or send revision notes.</p>
                      <Textarea
                        value={artifactReviewNotes.visualization}
                        onChange={(event) => setArtifactReviewNotes((previous) => ({ ...previous, visualization: event.target.value }))}
                        placeholder="Optional feedback (required if requesting changes)"
                        className="min-h-20"
                      />
                      <div className="flex gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          disabled={reviewSubmitting === "visualization"}
                          onClick={() => void handleArtifactReview("visualization", "approved")}
                        >
                          Approve visuals
                        </Button>
                        <Button
                          variant="destructive"
                          size="sm"
                          disabled={reviewSubmitting === "visualization"}
                          onClick={() => void handleArtifactReview("visualization", "changes_requested")}
                        >
                          Request changes
                        </Button>
                      </div>
                    </div>
                  )}
                </CardContent>
              ) : activePanel === "rehearsal" ? (
                <CardContent className="flex-1 overflow-y-auto space-y-4 pb-4">
                  {rehearsalError && (
                    <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30 text-sm text-destructive">
                      {rehearsalError}
                    </div>
                  )}
                  <VirtualRehearsalPanel
                    rehearsal={rehearsal}
                    isLoading={rehearsalLoading}
                    onGenerate={handleGenerateRehearsal}
                    onSpeakHostLine={speak}
                  />
                  {rehearsal && (
                    <div className="space-y-2 rounded-lg border border-border/60 p-3">
                      <p className="text-sm font-semibold">Client review</p>
                      <p className="text-xs text-muted-foreground">Approve this rehearsal flow or request adjustments.</p>
                      <Textarea
                        value={artifactReviewNotes.rehearsal}
                        onChange={(event) => setArtifactReviewNotes((previous) => ({ ...previous, rehearsal: event.target.value }))}
                        placeholder="Optional feedback (required if requesting changes)"
                        className="min-h-20"
                      />
                      <div className="flex gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          disabled={reviewSubmitting === "rehearsal"}
                          onClick={() => void handleArtifactReview("rehearsal", "approved")}
                        >
                          Approve rehearsal
                        </Button>
                        <Button
                          variant="destructive"
                          size="sm"
                          disabled={reviewSubmitting === "rehearsal"}
                          onClick={() => void handleArtifactReview("rehearsal", "changes_requested")}
                        >
                          Request changes
                        </Button>
                      </div>
                    </div>
                  )}
                </CardContent>
              ) : (
                <CardContent className="flex-1 overflow-y-auto space-y-4 pb-4">
                  <HumorAssistantPanel
                    suggestions={humorSuggestions}
                    speechDraft={speechDraft}
                    personality={personality}
                    onUpdatePersonality={(update) => setPersonality((prev) => ({ ...prev, ...update }))}
                    onGenerateHumor={generateHumor}
                    onGenerateSpeech={generateSpeech}
                    onSpeak={speak}
                  />
                </CardContent>
              )}

              {activePanel === "chat" && (
                <div className="border-t border-border/50 p-4 space-y-3">
                  {inputMode === "voice" && (
                    <div className="space-y-2">
                      {isListening && (
                        <div className="p-3 rounded-lg bg-blue-500/10 border border-blue-500/30">
                          <div className="flex items-center gap-2 text-blue-300 text-sm">
                            <Loader2 className="w-3 h-3 animate-spin" />
                            Listening...
                          </div>
                        </div>
                      )}

                      {transcript && (
                        <div className="p-3 rounded-lg bg-slate-700/40 border border-border">
                          <p className="text-sm text-muted-foreground">{transcript}</p>
                        </div>
                      )}

                      {transcript && !isListening && (
                        <Button onClick={() => void handleSubmitVoiceMessage()} disabled={isProcessing} className="w-full" variant="hero" size="sm">
                          <Send className="w-3 h-3 mr-2" />
                          Send Voice Message
                        </Button>
                      )}
                    </div>
                  )}

                  {inputMode === "text" && (
                    <div className="flex gap-2">
                      <input
                        type="text"
                        placeholder="Type your response..."
                        value={userMessage}
                        onChange={(e) => setUserMessage(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === "Enter" && !e.shiftKey) {
                            e.preventDefault();
                            void handleSendMessage();
                          }
                        }}
                        disabled={isProcessing}
                        className="flex-1 px-3 py-2 rounded-lg bg-slate-900 border border-border/50 text-sm placeholder-muted-foreground focus:outline-none focus:border-primary/50 transition disabled:opacity-50"
                      />
                      <Button onClick={() => void handleSendMessage()} disabled={isProcessing || !userMessage.trim()} size="sm" variant="hero">
                        <Send className="w-3 h-3" />
                      </Button>
                    </div>
                  )}

                  <div className="flex gap-2 justify-center">
                    <Badge
                      variant={inputMode === "text" ? "default" : "outline"}
                      className="cursor-pointer"
                      onClick={() => setInputMode("text")}
                    >
                      Text
                    </Badge>
                    <Badge
                      variant={inputMode === "voice" ? "default" : "outline"}
                      className={`cursor-pointer ${voiceReady ? "" : "opacity-50"}`}
                      onClick={() => voiceReady && setInputMode("voice")}
                    >
                      <Mic className="w-3 h-3 mr-1" />
                      Voice
                    </Badge>
                  </div>

                  {inputMode === "voice" && voiceReady && !isListening && (
                    <Button onClick={handleVoiceInput} disabled={isProcessing} className="w-full" variant="outline" size="sm">
                      <Mic className="w-3 h-3 mr-2" />
                      Start Listening
                    </Button>
                  )}

                  {isListening && (
                    <Button onClick={handleVoiceInput} disabled={isProcessing} className="w-full" variant="destructive" size="sm">
                      Stop Listening
                    </Button>
                  )}

                  {!timeline && (
                    <Button onClick={() => void handleGenerateTimeline()} disabled={timelineLoading} className="w-full" variant="outline" size="sm">
                      <CalendarDays className="w-3 h-3 mr-2" />
                      Generate Timeline from Conversation
                    </Button>
                  )}

                  {timeline && !storyboard && (
                    <Button
                      onClick={() => void handleGenerateVisualization()}
                      disabled={visualizationLoading}
                      className="w-full"
                      variant="outline"
                      size="sm"
                    >
                      <Image className="w-3 h-3 mr-2" />
                      Generate Visual Scenes
                    </Button>
                  )}
                  {timeline && storyboard && !rehearsal && (
                    <Button onClick={() => void handleGenerateRehearsal()} disabled={rehearsalLoading} className="w-full" variant="outline" size="sm">
                      <Clapperboard className="w-3 h-3 mr-2" />
                      Generate Virtual Rehearsal
                    </Button>
                  )}
                </div>
              )}
            </Card>

            <div className="mt-3 flex gap-2 justify-center flex-wrap">
              {plannerLoading && (
                <Badge variant="outline" className="bg-purple-500/20">
                  <Loader2 className="w-2 h-2 mr-1 animate-spin" /> Planning...
                </Badge>
              )}
              {timelineLoading && (
                <Badge variant="outline" className="bg-orange-500/20">
                  <Loader2 className="w-2 h-2 mr-1 animate-spin" /> Building timeline...
                </Badge>
              )}
              {visualizationLoading && (
                <Badge variant="outline" className="bg-pink-500/20">
                  <Loader2 className="w-2 h-2 mr-1 animate-spin" /> Rendering scenes...
                </Badge>
              )}
              {rehearsalLoading && (
                <Badge variant="outline" className="bg-indigo-500/20">
                  <Loader2 className="w-2 h-2 mr-1 animate-spin" /> Building rehearsal...
                </Badge>
              )}
              {isSpeaking && (
                <Badge variant="outline" className="bg-green-500/20">
                  <div className="w-2 h-2 mr-1 rounded-full bg-green-500" /> Speaking
                </Badge>
              )}
              {voiceReady && (
                <Badge variant="outline" className="bg-blue-500/20">
                  🎤 Voice Ready
                </Badge>
              )}
              {optimization && (
                <Badge variant="outline" className="bg-amber-500/20">
                  Timeline Score: {optimization.score}
                </Badge>
              )}
              {storyboard && <Badge variant="outline" className="bg-fuchsia-500/20">Scenes: {storyboard.scenes.length}</Badge>}
              {rehearsal && <Badge variant="outline" className="bg-indigo-500/20">Rehearsal: {rehearsal.runtimeSeconds}s</Badge>}
              {timeline && artifactReviewStatus.timeline !== "pending" && (
                <Badge variant="outline" className="bg-amber-500/20">Timeline {artifactReviewStatus.timeline === "approved" ? "approved" : "changes requested"}</Badge>
              )}
              {storyboard && artifactReviewStatus.visualization !== "pending" && (
                <Badge variant="outline" className="bg-pink-500/20">Visuals {artifactReviewStatus.visualization === "approved" ? "approved" : "changes requested"}</Badge>
              )}
              {rehearsal && artifactReviewStatus.rehearsal !== "pending" && (
                <Badge variant="outline" className="bg-indigo-500/20">Rehearsal {artifactReviewStatus.rehearsal === "approved" ? "approved" : "changes requested"}</Badge>
              )}
              {humorSuggestions.length > 0 && <Badge variant="outline" className="bg-teal-500/20">Humor lines: {humorSuggestions.length}</Badge>}
              {state.isComplete && <Badge className="bg-orange-500/20">✅ Plan Complete</Badge>}
            </div>
          </motion.div>
        </div>
      </div>
      <EntertainmentMomentWidget
        suggestion={moment}
        enabled={widgetEnabled}
        minimized={widgetMinimized}
        onRefresh={refreshMoment}
        onToggleEnabled={toggleWidgetEnabled}
        onToggleMinimized={toggleWidgetMinimized}
      />
    </div>
  );
}
